//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFrameGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeFrameGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;CodePack&gt; 
        ///  &lt;Code&gt; 
        ///    &lt;FunctionName&gt;判断素数fun_isPrime&lt;/FunctionName&gt;  
        ///    &lt;FunctionPrototype/&gt;  
        ///    &lt;Content&gt;int fun_isPrime(int n){
        ///    int i;
        ///    for (i=2;i&amp;lt;sqrt(n);i++){
        ///        if(n%2==0) return 1;
        ///    }
        ///    return 0;
        ///}&lt;/Content&gt; 
        ///  &lt;/Code&gt;  
        ///  &lt;Code&gt; 
        ///    &lt;FunctionName&gt;最大公因数fun_GCF&lt;/FunctionName&gt;  
        ///    &lt;FunctionPrototype/&gt;  
        ///    &lt;Content&gt;https://happylkx.gith ub.io&lt;/Content&gt; 
        ///  &lt;/Code&gt;  
        ///  &lt;Code&gt; 
        ///    &lt;FunctionName&gt;最小公倍数fun_LCM&lt;/Functio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FunctionsSource {
            get {
                return ResourceManager.GetString("FunctionsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mm_facetoface_collect_qrcode_1540912042369 {
            get {
                object obj = ResourceManager.GetObject("mm_facetoface_collect_qrcode_1540912042369", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
